### ISSUE TITLE
Password in plaintext in bash script

### ISSUE THREAD

**Issue by MaiaBlanco** [SLDatCMU/BLE_Campus_Mobility_Sensing#1]
Looks like a plaintext password is written into the shell script here. I suggest some other way of logging in, such as using an identity key file for ssh. We don't have a license for a private organization on Github, so the repository is unfortunately public.

* [Alert script](https://github.com/SLDatCMU/BLE_Campus_Mobility_Sensing/blob/master/alert.sh)
* [Data collection script](https://github.com/SLDatCMU/BLE_Campus_Mobility_Sensing/blob/master/collect-daily.sh)
* [Mail setup script](https://github.com/SLDatCMU/BLE_Campus_Mobility_Sensing/blob/master/mail-setup.sh)
* [Node setup script](https://github.com/SLDatCMU/BLE_Campus_Mobility_Sensing/blob/master/node-setup.sh)

**Comment by MaiaBlanco** [comment]
Pointers to use identity file to log in to nodes from your laptop without a password: https://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/

**Comment by pengzai6666** [comment]
Thank you Mark for your good advice! I believe the problem has been solved, sorry for the confusion.
